kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "productopener.fullname" . }}-images
  labels:
    app: {{ include "productopener.name" . }}
    chart: {{ include "productopener.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: default-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  hostPath:
    path: /po/images